---
- name: Install R and required packages on Ubuntu
  hosts: all
  become: yes
  tasks:
    - name: Get release name
      shell: lsb_release -sc
      register: release_name

    - name: Print release name
      debug:
        msg: "RELEASE_NAME = {{ release_name.stdout }}"

    - name: Import R repository key
      apt_key:
        keyserver: keyserver.ubuntu.com
        id: E298A3A825C0D65DFD57CBB651716619E084DAB9
        state: present

    - name: Add R repository
      apt_repository:
        repo: "deb https://cloud.r-project.org/bin/linux/ubuntu {{ release_name.stdout }}-cran40/"
        state: present
        update_cache: yes

    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Install R and dependencies
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - r-base-dev
        - curl
        - libcurl4-openssl-dev
        - libxml2-dev
        - libssl-dev

    - name: Check R version
      command: R --version
