---
- name: Install Deno
  hosts: localhost
  become: yes

  tasks:
    - name: Install Deno using install.sh script
      ansible.builtin.shell: |
        curl -fsSL https://deno.land/x/install/install.sh | sh -s v1.7.5

    - name: Create directory for Deno binaries
      ansible.builtin.file:
        path: /opt/deno
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Move Deno binaries to /opt/deno
      ansible.builtin.command:
        cmd: sudo mv ~/.deno/* /opt/deno
        args:
          creates: /opt/deno/bin/deno

    - name: Set Deno alternatives
      ansible.builtin.alternatives:
        name: deno
        link: /usr/bin/deno
        path: /opt/deno/bin/deno
        priority: 50

    - name: Verify Deno installation
      ansible.builtin.command: deno --version
