---
- name: Install Docker on Ubuntu
  hosts: localhost
  become: yes

  tasks:
    - name: Update APT package index
      apt:
        update_cache: yes

    - name: Install prerequisite packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common

    - name: Determine Ubuntu version
      set_fact:
        ubuntu_codename: "{{ ansible_distribution_release }}"

    - name: Add Docker GPG key
      shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch={{ dpkg_architecture }} signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ubuntu_codename }} stable"
        state: present

    - name: Update APT package index (again)
      apt:
        update_cache: yes

    - name: Determine latest Docker CE version available
      shell: apt-cache madison docker-ce | awk 'NR==1{print $3}'
      register: docker_ce_version

    - name: Install Docker CE
      apt:
        name: docker-ce={{ docker_ce_version.stdout }}
        state: present

    - name: Start Docker service and enable on boot
      service:
        name: docker
        state: started
        enabled: yes

    - name: Check Docker service status
      systemd:
        name: docker
        state: started

    - name: Display Docker version
      command: docker --version
      register: docker_version

    - debug:
        msg: "Docker version is {{ docker_version.stdout }}"
