---
- name: Install Code::Blocks and wxWidgets on Ubuntu
  hosts: localhost
  become: yes

  tasks:
    - name: Install the compiler
      apt:
        name: build-essential
        state: present
        update_cache: yes

    - name: Install the debugger
      apt:
        name: gdb
        state: present

    - name: Install wxWidgets library
      apt:
        name:
          - libwxgtk3.0-gtk3-dev
          - libwxgtk3.0-gtk3-0v5
        state: present

    - name: Add Code::Blocks PPA repository
      apt_repository:
        repo: ppa:codeblocks-devs/release
        state: present

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install the latest Code::Blocks release
      apt:
        name: codeblocks
        state: present
