version: "3"

networks:
  gitea_default:
    external: false

services:
  server:
    image: gitea/gitea:1.17-dev
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
    networks:
      - gitea_default
    volumes:
      - /media/thom/seagate01/gitea/data:/data
      - /media/thom/seagate01/gitea/timezone:/etc/timezone:ro
      - /media/thom/seagate01/gitea/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"
