---
- name: Install NVIDIA Container Toolkit
  hosts: all
  become: yes
  tasks:
    - name: Setup NVIDIA Container Toolkit repository GPG key
      shell: |
        distribution=$(. /etc/os-release; echo $ID$VERSION_ID)
        curl -s -L https://nvidia.github.io/libnvidia-container/gpgkey | sudo apt-key add -
      register: setup_gpg_key
      changed_when: setup_gpg_key.stdout != ""

    - name: Setup NVIDIA Container Toolkit repository
      shell: |
        distribution=$(. /etc/os-release; echo $ID$VERSION_ID)
        curl -s -L "https://nvidia.github.io/libnvidia-container/$distribution/libnvidia-container.list" | sudo tee /etc/apt/sources.list.d/nvidia-container-toolkit.list
      register: setup_repository
      changed_when: setup_repository.stdout != ""

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install NVIDIA Container Toolkit
      apt:
        name: nvidia-container-toolkit
        state: present
      register: install_toolkit
      changed_when: install_toolkit.changed

    - name: Print installation status
      debug:
        msg: "NVIDIA Container Toolkit installation {{ 'succeeded' if install_toolkit.changed else 'skipped' }}"

