---
- name: Install CMake
  hosts: localhost
  become: yes

  vars:
    cmake_version: "3.16.9"

  tasks:
    - name: Uninstall old cmake
      apt:
        name: cmake
        state: absent

    - name: Download the latest CMake tarball
      get_url:
        url: "https://github.com/Kitware/CMake/releases/download/v{{ cmake_version }}/cmake-{{ cmake_version }}-linux-x86_64.tar.gz"
        dest: "/tmp/cmake-{{ cmake_version }}-linux-x86_64.tar.gz"

    - name: Create installation directory
      file:
        path: "/opt/cmake/v{{ cmake_version }}"
        state: directory

    - name: Extract CMake tarball
      unarchive:
        src: "/tmp/cmake-{{ cmake_version }}-linux-x86_64.tar.gz"
        dest: "/opt/cmake/v{{ cmake_version }}"
        remote_src: yes

    - name: Erase existing update-alternatives setup for cmake
      command: update-alternatives --remove-all cmake
      ignore_errors: yes

    - name: Erase existing update-alternatives setup for ctest
      command: update-alternatives --remove-all ctest
      ignore_errors: yes

    - name: Erase existing update-alternatives setup for cpack
      command: update-alternatives --remove-all cpack
      ignore_errors: yes

    - name: Install cmake alternative (priority 60)
      alternatives:
        name: cmake
        link: /usr/bin/cmake
        path: "/opt/cmake/v{{ cmake_version }}/bin/cmake"
        priority: 60

    - name: Install ctest alternative (priority 60)
      alternatives:
        name: ctest
        link: /usr/bin/ctest
        path: "/opt/cmake/v{{ cmake_version }}/bin/ctest"
        priority: 60

    - name: Install cpack alternative (priority 60)
      alternatives:
        name: cpack
        link: /usr/bin/cpack
        path: "/opt/cmake/v{{ cmake_version }}/bin/cpack"
        priority: 60

    - name: Configure cmake alternatives
      command: update-alternatives --config cmake

    - name: Test cmake version
      command: cmake --version
