---
- name: Install PyCharm on Linux Mint using alternatives
  hosts: localhost

  tasks:
  - name: "Uninstall old cmake"
      sudo apt remove cmake

  - name: "download the latest bash script from cmake.org"
    ansible.builtin.download:
      url: https://github.com/Kitware/CMake/releases/download/v3.16.9/cmake-3.16.9-linux-x86_64.tar.gz

  - name: "Copy to /opt"
    ansible.builtin.copy:
      src: cmake-3.16.9-linux-x86_64.tar.gz
      dest: /opt/cmake/v3.16.9

  - name: "Make the script executable"
    ansible.builtin.file:
      path: "/opt/cmake-3.16.9-linux-x86_64.sh"
      mode: u+x

  - name: "Change to desired installation directory"
    ansible.builtin.command:
      run: sudo mkdir -p /opt/cmake/v3.16.9

  - name: "run installation"
    ansible.builtin.command:
      run: sudo bash /opt/cmake-$VERSION-linux-x86_64.sh --prefix=/opt/cmake/v3.16.9 --skip-license

  - name: "erase exiting update-alternatives setup"
    ansible.builtin.command:
      run: |
        sudo update-alternatives --remove-all cmake
        sudo update-alternatives --remove-all ctest
        sudo update-alternatives --remove-all cpack

  - name: "Install Alternatives"
    ansible.builtin.alternatives:
      name: cmake
      link: /usr/bin/cmake
      path: "/opt/cmake/cmake-3.24/bin/cmake"
      priority: 50

    ansible.builtin.alternatives:
        name: cmake
        link: /usr/bin/cmake
        path: "/opt/cmake/cmake-3.16/bin/cmake"
        priority: 40

    ansible.builtin.alternatives:
        name: cmake
        link: /usr/bin/cmake
        path: "/opt/cmake/cmake-3.26/bin/cmake"
        priority: 60

    ansible.builtin.alternatives:
        name: ctest
        link: /usr/bin/ctest
        path: "/opt/cmake/cmake-3.24/bin/ctest"
        priority: 50

    ansible.builtin.alternatives:
        name: ctest
        link: /usr/bin/ctest
        path: "/opt/cmake/cmake-3.26/bin/ctest"
        priority: 60

    ansible.builtin.alternatives:
        name: cpack
        link: /usr/bin/cpack
        path: "/opt/cmake/cmake-3.24/bin/cpack"
        priority: 50

    ansible.builtin.alternatives:
        name: cpack
        link: /usr/bin/cpack
        path: "/opt/cmake/cmake-3.26/bin/cpack"
        priority: 60


  - name: # Configure Alternatives
      # configuring the default commands for gcc, g++. It's easy to switch interactively:
      sudo update-alternatives --config cmake

  - name: #Test your results with:
      cmake --version
