---
- name: Install Balena Etcher
  hosts: localhost
  become: yes
  tasks:
    - name: Create directory for Balena Etcher
      file:
        path: /opt/etcher/v1.19.21/bin
        state: directory
        mode: '0755'

    - name: Download Balena Etcher
      get_url:
        url: https://github.com/balena-io/etcher/releases/download/v1.19.21/balenaEtcher-linux-x64-1.19.21.zip
        dest: /tmp/balenaEtcher-linux-x64-1.19.21.zip
        mode: '0644'

    - name: Unzip Balena Etcher
      ansible.builtin.unarchive:
        src: /tmp/balenaEtcher-linux-x64-1.19.21.zip
        dest: /opt/etcher/v1.19.21/bin
        remote_src: yes
        creates: /opt/etcher/v1.19.21/bin/balenaEtcher

    - name: Set up alternatives for Balena Etcher
      ansible.builtin.alternatives:
        name: etcher
        link: /usr/local/bin/etcher
        path: /opt/etcher/v1.19.21/bin/balenaEtcher
        priority: 100
        state: present

    - name: Verify Balena Etcher installation
      command: etcher --version
      register: etcher_version_output

    - name: Display Balena Etcher version
      debug:
        msg: "Balena Etcher version is {{ etcher_version_output.stdout }}"

    - name: Clean up downloaded zip file
      file:
        path: /tmp/balenaEtcher-linux-x64-1.19.21.zip
        state: absent
