---
- name: Reinstall Wi-Fi drivers
  hosts: all
  become: yes
  tasks:
    - name: Ensure necessary packages are installed
      apt:
        name:
          - build-essential
          - dkms
          - git
        state: present

    - name: Remove existing rtl8812au-dkms package
      apt:
        name: rtl8812au-dkms
        state: absent

    - name: Clone rtl8812au repository
      git:
        repo: https://github.com/aircrack-ng/rtl8812au.git
        dest: /tmp/rtl8812au
        update: yes

    - name: Change directory to rtl8812au
      command: chdir=/tmp/rtl8812au pwd
      register: rtl8812au_path

    - name: Remove existing dkms module
      make:
        chdir: "{{ rtl8812au_path.stdout }}"
        target: dkms_remove

    - name: Install dkms module
      make:
        chdir: "{{ rtl8812au_path.stdout }}"
        target: dkms_install

    - name: Restart NetworkManager service
      service:
        name: NetworkManager
        state: restarted

    - name: Clean up rtl8812au directory
      file:
        path: /tmp/rtl8812au
        state: absent
        recurse: yes
