---
- name: Install Node.js LTS and npm using Ansible
  hosts: localhost
  become: yes  # Ensure Ansible executes commands with sudo

  tasks:
    - name: Add Node.js repository key
      apt_key:
        url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
        state: present

    - name: Add Node.js LTS repository
      apt_repository:
        repo: deb https://deb.nodesource.com/node_14.x focal main  # Adjust for your Ubuntu version if necessary
        state: present

    - name: Install Node.js, npm, and build-essential
      apt:
        name:
          - nodejs
          - npm
          - build-essential
        state: present
        update_cache: yes
