version: '3'
services:
  some-rabbitmq:
    image: rabbitmq:3-management-alpine
    hostname: rabbit-host
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - "./enabled_plugins:/etc/rabbitmq/enabled_plugins"