
bootstrap:
    ansible.sh

node:
	ansible-playbook -i inventory.ini node-js/node-js_playbook.yaml

pycharm:
	ansible-playbook -i inventory.ini pycharm/pycharm-playbook.yaml

aws:
	ansible-playbook -i inventory.ini aws/aws-playbook.yaml

bazel:
	ansible-playbook -i inventory.ini bazel/bazel-playbook.yaml

code:
	ansible-playbook -i inventory.ini code/code-playbook.yaml

firefox:
	ansible-playbook -i inventory.ini firefox/firefox-playbook.yaml

goofys:
	ansible-playbook -i inventory.ini goofys/goofys-playbook.yaml

hugo:
	ansible-playbook -i inventory.ini hugo/hugo-playbook.yaml

idea:
	ansible-playbook -i inventory.ini idea/idea-playbook.yaml

julia:
	ansible-playbook -i inventory.ini julia/julia-playbook.yaml

pnpm:
	ansible-playbook -i inventory.ini pnpm/pnpm-playbook.yaml

rclone:
	ansible-playbook -i inventory.ini rclone/rclone-playbook.yaml

saml2aws:
	ansible-playbook -i inventory.ini saml2aws/saml2aws-playbook.yaml

terraform:
	ansible-playbook -i inventory.ini terraform/terraform-playbook.yaml

terraformer:
	ansible-playbook -i inventory.ini terraformer/terraformer-playbook.yaml

vscode:
	ansible-playbook -i inventory.ini vscode/vscode-playbook.yaml
