---
- name: Install OpenJDK 8 and configure JAVA_HOME
  hosts: localhost
  become: yes  # This allows Ansible to execute commands with sudo

  tasks:
    - name: Install OpenJDK 8
      apt:
        name: openjdk-8-jdk
        state: present
      environment:
        DEBIAN_FRONTEND: noninteractive

    - name: Set JAVA_HOME in /etc/environment
      lineinfile:
        path: /etc/environment
        line: 'JAVA_HOME="/usr/lib/jvm/java-8-openjdk-amd64"'
        state: present

    - name: Export JAVA_HOME for current session
      ansible.builtin.export:
        variable: JAVA_HOME
        value: /usr/lib/jvm/java-8-openjdk-amd64

    - name: Run R CMD javareconf
      command: sudo R CMD javareconf
      environment:
        JAVA_HOME: /usr/lib/jvm/java-8-openjdk-amd64
