---
- name: Install GCC 8 from local .deb files
  hosts: all
  become: yes
  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install GCC 8 base
      apt:
        deb: ./gcc-8-base_8.4.0-3ubuntu2_amd64.deb
        state: present

    - name: Install libmpx2
      apt:
        deb: ./libmpx2_8.4.0-3ubuntu2_amd64.deb
        state: present

    - name: Install lib32mpx2
      apt:
        deb: ./lib32mpx2_8.4.0-3ubuntu2_amd64.deb
        state: present

    - name: Install remaining packages
      apt:
        deb: "{{ item }}"
        state: present
      with_items:
        - ./libisl22_0.22.1-1_amd64.deb
        - ./lib32gcc-8-dev_8.4.0-3ubuntu2_amd64.deb
        - ./libx32gcc-8-dev_8.4.0-3ubuntu2_amd64.deb
        - ./libstdc++-8-dev_8.4.0-3ubuntu2_amd64.deb
        - ./gcc-8-multilib_8.4.0-3ubuntu2_amd64.deb
        - ./lib32stdc++-8-dev_8.4.0-3ubuntu2_amd64.deb
        - ./libx32stdc++-8-dev_8.4.0-3ubuntu2_amd64.deb
        - ./cpp-8_8.4.0-3ubuntu2_amd64.deb
        - ./libgcc-8-dev_8.4.0-3ubuntu2_amd64.deb
        - ./gcc-8_8.4.0-3ubuntu2_amd64.deb
        - ./g++-8_8.4.0-3ubuntu2_amd64.deb
        - ./g++-8-multilib_8.4.0-3ubuntu2_amd64.deb

    - name: Ensure GCC 8 is set as the default GCC version
      alternatives:
        name: gcc
        link: /usr/bin/gcc
        path: /usr/bin/gcc-8
        priority: 100

    - name: Ensure G++ 8 is set as the default G++ version
      alternatives:
        name: g++
        link: /usr/bin/g++
        path: /usr/bin/g++-8
        priority: 100

    - name: Verify GCC installation
      command: gcc-8 --version

    - name: Verify G++ installation
      command: g++-8 --version
