---
- name: Install ceph
  hosts: localhost

  tasks:
    - name: "download gpg key"
      ansible.builtin.command:
        run: wget -q -O- 'https://download.ceph.com/keys/release.asc' | sudo apt-key add -

    - name: "add key to sources list"
      ansible.builtin.command:
        run: echo deb https://download.ceph.com/debian-{ceph-stable-release}/ $(lsb_release -sc) main | sudo tee /etc/apt/sources.list.d/ceph.list

    - name:
      ansible.builtin.command:
        run: sudo apt update

    - name:
      ansible.builtin.command:
        run: sudo apt install ceph-deploy

    - name:
      ansible.builtin.command:
        run: sudo apt install ntpsec

    - name:
      ansible.builtin.command:
        run: sudo apt install openssh-server
