---
- name: Install Ceph
  hosts: localhost

  tasks:
    - name: Download and add the Ceph GPG key
      apt_key:
        url: https://download.ceph.com/keys/release.asc
        state: present

    - name: Add Ceph repository to sources list
      apt_repository:
        repo: "deb https://download.ceph.com/debian-{ceph-stable-release}/ $(lsb_release -sc) main"
        state: present

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install ceph-deploy
      apt:
        name: ceph-deploy
        state: present

    - name: Install ntpsec
      apt:
        name: ntpsec
        state: present

    - name: Install openssh-server
      apt:
        name: openssh-server
        state: present
