---
- name: Export GPG key from deprecated keyring and update APT source
  hosts: localhost
  become: yes
  tasks:
    - name: List existing keys
      command: apt-key list
      register: apt_key_list

    - name: Extract last 8 characters of the desired GPG key
      set_fact:
        gpg_key_last8: "{{ apt_key_list.stdout | regex_search('\\s([A-Z0-9]{8})\\s', '\\1') }}"

    - name: Export GPG key to /usr/share/keyrings
      ansible.builtin.command: "sudo apt-key export {{ gpg_key_last8 }} | sudo gpg --dearmour -o /usr/share/keyrings/{{ gpg_key_last8 }}.gpg"

    - name: Update APT source file
      ansible.builtin.lineinfile:
        path: /etc/apt/sources.list.d/microsoft.list  # Update with your actual file path
        line: "deb [arch=amd64 signed-by=/usr/share/keyrings/{{ gpg_key_last8 }}.gpg] https://packages.microsoft.com/repos/edge/ stable main"
        create: yes

    - name: Update APT
      ansible.builtin.command: sudo apt update

    - name: Remove original signature
      ansible.builtin.command: sudo apt-key del {{ gpg_key_last8 }}
