---
- name: Install TiMidity++ and configure as a service
  hosts: all
  become: yes
  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install TiMidity++
      apt:
        name: timidity
        state: present

    - name: Create the TiMidity++ systemd service file
      copy:
        src: timidity.service
        dest: /etc/systemd/system/timidity.service
        mode: '0644'

    - name: Reload systemd to apply changes
      command: systemctl daemon-reload

    - name: Enable TiMidity++ service
      systemd:
        name: timidity
        enabled: yes

    - name: Start TiMidity++ service
      systemd:
        name: timidity
        state: started

    - name: Verify TiMidity++ service is running
      command: systemctl status timidity
      register: timidity_status

    - name: Display TiMidity++ service status
      debug:
        msg: "{{ timidity_status.stdout }}"
