---
- name: Install VSCodium on Ubuntu
  hosts: localhost
  become: yes

  tasks:
    - name: Update the package list
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: dist
        update_cache: yes

    - name: Add VSCodium GPG key
      ansible.builtin.shell: |
        wget -qO - https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg | gpg --dearmor | sudo dd of=/usr/share/keyrings/vscodium-archive-keyring.gpg
      args:
        executable: /bin/bash

    - name: Add VSCodium repository
      ansible.builtin.shell: |
        echo 'deb [signed-by=/usr/share/keyrings/vscodium-archive-keyring.gpg] https://download.vscodium.com/debs vscodium main' | sudo tee /etc/apt/sources.list.d/vscodium.list
      args:
        executable: /bin/bash

    - name: Update the package list again
      apt:
        update_cache: yes

    - name: Install VSCodium
      apt:
        name: codium
        state: present
