---
- name: Install Intel GPU Software Packages on Ubuntu 20.04
  hosts: localhost
  become: yes

  tasks:
    - name: Install prerequisite packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - gpg-agent
        - wget

    - name: Add Intel graphics repository key
      shell: wget -qO - https://repositories.intel.com/graphics/intel-graphics.key | sudo apt-key add -
      args:
        warn: false

    - name: Add Intel graphics repository
      apt_repository:
        repo: 'deb [arch=amd64] https://repositories.intel.com/graphics/ubuntu focal main'
        state: present

    - name: Update apt repositories
      apt:
        update_cache: yes

    - name: Install runtime packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - intel-opencl-icd
        - intel-level-zero-gpu
        - level-zero
        - intel-media-va-driver-non-free
        - libmfx1

    - name: Install developer packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - libigc-dev
        - intel-igc-cm
        - libigdfcl-dev
        - libigfxcmrt-dev
        - level-zero-dev

    - name: Configure GPU access permissions
      shell: |
        sudo gpasswd -a {{ ansible_user }} render
        newgrp render
      args:
        executable: /bin/bash
