---
- name: Install CUDA 11.2.0 Toolkit using Ansible
  hosts: localhost
  become: yes  # Ensure Ansible executes commands with sudo

  tasks:
    - name: Download CUDA installer
      get_url:
        url: https://developer.download.nvidia.com/compute/cuda/11.2.0/local_installers/cuda_11.2.0_460.27.04_linux.run
        dest: /tmp/cuda_11.2.0_460.27.04_linux.run

    - name: Set executable permissions on CUDA installer
      file:
        path: /tmp/cuda_11.2.0_460.27.04_linux.run
        mode: +x

    - name: Install CUDA Toolkit
      shell: /tmp/cuda_11.2.0_460.27.04_linux.run --toolkit --silent
      args:
        executable: /bin/bash

    - name: Add CUDA binaries to PATH
      lineinfile:
        dest: ~/.bashrc  # Adjust this path if needed (e.g., /home/user/.bashrc)
        line: 'export PATH=$PATH:/usr/local/cuda/bin'
        insertafter: EOF

    - name: Add CUDA library path to LD_LIBRARY_PATH
      lineinfile:
        dest: ~/.bashrc  # Adjust this path if needed (e.g., /home/user/.bashrc)
        line: 'export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda/lib64'
        insertafter: EOF

    - name: Source .bashrc to apply changes immediately
      shell: source ~/.bashrc
      args:
        executable: /bin/bash
        creates: ~/.bashrc  # Ensures it runs only once per playbook execution
