---
- name: Install jamovi via Flatpak
  hosts: localhost
  become: yes  # This allows Ansible to execute commands with sudo

  tasks:
    - name: Install flatpak and gnome-software-plugin-flatpak
      apt:
        name:
          - flatpak
          - gnome-software-plugin-flatpak
        state: present
      environment:
        DEBIAN_FRONTEND: noninteractive

    - name: Add Flathub remote repository
      shell: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

    - name: Install jamovi from Flathub
      shell: flatpak install -y flathub org.jamovi.jamovi

    - name: Ensure flatpak apps are discoverable in GNOME Software
      shell: flatpak --system repair --user

    - name: Restart GNOME Software for changes to take effect
      shell: systemctl restart gnome-software

    - name: Add shortcut to desktop (optional)
      copy:
        content: |
          [Desktop Entry]
          Name=jamovi
          Exec=flatpak run org.jamovi.jamovi
          Icon=org.jamovi.jamovi
          Terminal=false
          Type=Application
          Categories=Education;Science;
        dest: /usr/share/applications/org.jamovi.jamovi.desktop
        mode: 0644
      notify: Refresh GNOME desktop

  handlers:
    - name: Refresh GNOME desktop
      shell: dbus-launch --exit-with-session gnome-shell --replace &

