services:
  mosquitto:
    restart: unless-stopped
    image: eclipse-mosquitto:2.0.15
    volumes:
      - ./config/:/mosquitto/config/:rw
      - ./log/:/mosquitto/log/
      - data:/mosquitto/data/
    ports:
      - 1883:1883
      - 9001:9001

volumes:
  data: ~
