---
- name: Install Jupyter IRKernel for R
  hosts: localhost
  become: yes  # Ensure Ansible executes commands with sudo

  tasks:
    - name: Install R and required packages
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      with_items:
        - r-base
        - libzmq3-dev  # Required for Jupyter
        - libcurl4-openssl-dev  # Required for IRkernel installation in R

    - name: Install IRkernel using R
      ansible.builtin.command: R -e 'install.packages("IRkernel")'

    - name: Make IRkernel available to Jupyter
      ansible.builtin.command: R -e 'IRkernel::installspec(user = FALSE)'

    - name: Install Jupyter labextension for text shortcuts
      ansible.builtin.command: jupyter labextension install @techrah/text-shortcuts
      args:
        creates: /home/{{ ansible_user }}/.local/share/jupyter/labextensions/@techrah/text-shortcuts

    - name: Restart Jupyter for changes to take effect
      ansible.builtin.systemd:
        name: jupyter
        state: restarted
