---
- name: Install NVIDIA cuDNN 8.0.4.30 using Ansible
  hosts: localhost
  become: yes  # Ensure Ansible executes commands with sudo

  vars:
    basedir: /media/thom/seagate01/software/nvidia-cudnn
    basepath: cudnn-10.2-linux-x64-v8.0.4.30
    tgzfile: "{{ basepath }}.tgz"

  tasks:
    - name: Ensure cuDNN archive is downloaded (uncomment to download)
      # uncomment below to download the file
      # shell: wget https://developer.nvidia.com/compute/machine-learning/cudnn/secure/8.0.4/10.2_20200923/{{ tgzfile }} -P {{ basedir }}
      # args:
      #   creates: "{{ basedir }}/{{ tgzfile }}"
      #   executable: /bin/bash
      #   warn: no

    - name: Extract cuDNN archive
      shell: tar -xzvf "{{ basedir }}/{{ tgzfile }}" -C {{ basedir }}
      args:
        executable: /bin/bash

    - name: Copy cuDNN headers to CUDA include directory
      shell: sudo cp -r {{ basedir }}/{{ basepath }}/cuda/include/* /usr/local/cuda/include
      args:
        executable: /bin/bash

    - name: Copy cuDNN libraries to CUDA lib64 directory
      shell: sudo cp -r {{ basedir }}/{{ basepath }}/cuda/lib64/* /usr/local/cuda/lib64
      args:
        executable: /bin/bash

    - name: Set permissions for CUDA directory
      shell: sudo chmod -R a+r /usr/local/cuda
      args:
        executable: /bin/bash

    - name: Check cuDNN installation
      shell: cat /usr/local/cuda/include/cudnn.h | grep CUDNN_MAJOR -A 2
      args:
        executable: /bin/bash
