version: "3.9"
services:
  nginx:
    image: nginx:1.25.4-alpine
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8000:80"
  label-studio:
    user: "${UID}:${GID}"
    stdin_open: true
    tty: true
    image: heartexlabs/label-studio:1.11.0
    restart: unless-stopped
    expose: [ 8000 ]
    command: label-studio-uwsgi
