---
- name: Install XRDP
  hosts: all
  become: yes
  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install Ubuntu desktop environment (if not already installed)
      apt:
        name: ubuntu-desktop
        state: present
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_version | version_compare('20.04', '>=')

    - name: Install XRDP
      apt:
        name: xrdp
        state: present

    - name: Add current user to ssl-cert group
      shell: adduser $USER ssl-cert

    - name: Restart XRDP service
      systemd:
        name: xrdp
        state: restarted
        enabled: yes

    - name: Allow XRDP port 3389 in UFW
      ufw:
        rule: allow
        port: 3389

    - name: Reload UFW
      command: ufw reload
