---
- name: Install MPI and OpenCoarrays compilers on Ubuntu
  hosts: localhost
  become: yes
  tasks:
    - name: Install MPI dependencies
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop:
        - libopenmpi-dev
        - openmpi-bin
        - gfortran
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_major_version | int >= 12

    - name: Install OpenCoarrays compiler
      ansible.builtin.package:
        name: open-coarrays-bin
        state: present
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_major_version | int >= 17
