---
- name: Install pipx and DVC
  hosts: localhost
  become: yes
  tasks:
    - name: Install pipx
      apt:
        name: pipx
        state: present
        update_cache: yes

    - name: Ensure pipx paths are configured
      command: pipx ensurepath
      become_user: root

    - name: Install DVC using pipx
      pipx:
        name: dvc
        state: present

    - name: Check DVC version
      command: dvc --version
      register: dvc_version_output

    - name: Display DVC version
      debug:
        msg: "DVC version is {{ dvc_version_output.stdout }}"
