version: "3"
services:

  minioblobstore:
    image: minio/minio:RELEASE.2020-12-29T23-29-29Z
    user: $UID:$GID
    ports:
      - 9000:9000
    restart: unless-stopped
    env_file: .env
    environment:
      MINIO_ACCESS_KEY: $MINIO_ACCESS_KEY
      MINIO_SECRET_KEY: $MINIO_SECRET_KEY
    volumes:
      - /home/thom/.minio:/home/$USER/.minio
      - /mnt/seagateA/minio:/home/$USER/seagateA
      - /mnt/seagateB/minio:/home/$USER/seagateB
      - /mnt/seagates/minio:/home/$USER/seagates
      - /mnt/seagate2/minio:/home/$USER/seagate2
      - /mnt/ULTRA/minio:/home/$USER/ULTRA
      - /mnt/seagates3/minio:/home/$USER/seagates3
      - /mnt/HDD0/minio:/home/$USER/HDD0
      - /mnt/HDD1/minio:/home/$USER/HDD1
    command: server /home/$USER/seagateA /home/$USER/seagateB /home/$USER/seagates /home/$USER/seagate2 /home/$USER/ULTRA /home/$USER/seagates3 /home/$USER/HDD0 /home/$USER/HDD1
