---
- name: Install and Configure MinIO
  hosts: localhost
  become: yes  # Ensure Ansible executes commands with sudo

  tasks:
    - name: Download MinIO server
      get_url:
        url: "https://dl.min.io/server/minio/release/linux-amd64/minio"
        dest: "/usr/local/bin/minio"
        mode: "0755"

    - name: Download MinIO client (mc)
      get_url:
        url: "https://dl.min.io/client/mc/release/linux-amd64/mc"
        dest: "/usr/local/bin/mc"
        mode: "0755"

    - name: Download MinIO systemd service file
      get_url:
        url: "https://raw.githubusercontent.com/minio/minio-service/master/linux-systemd/minio.service"
        dest: "/etc/systemd/system/minio.service"
        mode: "0644"

    - name: Configure MinIO environment variables
      blockinfile:
        path: "{{ ansible_env.HOME }}/.bashrc"
        block: |
          export MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE
          export MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
        marker: "# {mark} ANSIBLE MANAGED BLOCK"

    - name: Configure MinIO client
      command: >
        mc config host add --quiet --api s3v4 minioblobstore
        http://localhost:9000 {{ lookup('env', 'MINIO_ACCESS_KEY') }}
        {{ lookup('env', 'MINIO_SECRET_KEY') }}
      environment:
        HOME: "{{ ansible_env.HOME }}"

    - name: Start MinIO server
      systemd:
        name: minio
        state: started
        enabled: yes
