---
- name: Install Insomnia
  hosts: localhost
  become: yes

  tasks:
    - name: Add Insomnia repository to sources
      ansible.builtin.copy:
        content: "deb https://dl.bintray.com/getinsomnia/Insomnia /"
        dest: "/etc/apt/sources.list.d/insomnia.list"
        owner: root
        group: root
        mode: '0644'

    - name: Add Insomnia public key
      ansible.builtin.get_url:
        url: "https://insomnia.rest/keys/debian-public.key.asc"
        dest: "/tmp/insomnia-public-key.asc"

    - name: Import Insomnia public key
      ansible.builtin.shell: "sudo apt-key add /tmp/insomnia-public-key.asc"

    - name: Update apt repositories
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Insomnia
      ansible.builtin.apt:
        name: insomnia
        state: present
        update_cache: yes
