version: "3"
services:
  cassandra:
    image: cassandra:3.11.4
    ports:
      - 7000:7000
      - 7001:7001
      - 7199:7199
      - 9042:9042
      - 9160:9160
    restart: unless-stopped

  cassandra-web:
    image: markusgulden/cassandra-web
    depends_on: [ cassandra ]
    environment:
      CASSANDRA_HOST_IPS: cassandra
      CASSANDRA_PORT: 9042
      CASSANDRA_USER: "cassandra"
      CASSANDRA_PASSWORD: "cassandra"
    ports:
      - 3000:3000