---
- name: Install Visual Studio Code
  hosts: all
  become: yes
  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Download Visual Studio Code
      get_url:
        url: https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64
        dest: /tmp/code_latest_amd64.deb

    - name: Install Visual Studio Code
      apt:
        deb: /tmp/code_latest_amd64.deb
        state: present

    - name: Remove the downloaded .deb file
      file:
        path: /tmp/code_latest_amd64.deb
        state: absent

    - name: Verify Visual Studio Code installation
      command: code --version
      register: vscode_version

    - name: Display Visual Studio Code version
      debug:
        msg: "Installed Visual Studio Code version: {{ vscode_version.stdout }}"

    - name: Install PyCharm desktop entry
      ansible.builtin.copy:
        content: "{{ lookup('file', 'com.microsoft.vs.code.desktop') }}"
        dest: "{{ lookup('env', 'HOME') }}/.local/share/applications/vscode.desktop"
