version: "3"

services:
  minio:
    image: minio/minio:RELEASE.2020-12-29T23-29-29Z
    env_file: .env
    ports:
      - 9000:9000
    environment:
      MINIO_ACCESS_KEY: $MINIO_ACCESS_KEY
      MINIO_SECRET_KEY: $MINIO_SECRET_KEY
    command: server /data

  mlflow:
    depends_on: [ minio ]
    image: larribas/mlflow:latest
    env_file: .env
    ports:
      - 5000:5000
    environment:
      MLFLOW_S3_ENDPOINT_URL: minio:9000
      AWS_ACCESS_KEY_ID: $MINIO_ACCESS_KEY
      AWS_SECRET_ACCESS_KEY: $MINIO_SECRET_KEY
    entrypoint: mlflow server --host 0.0.0.0 --default-artifact-root s3://mlflow