---
- name: Install MuJoCo and mujoco-py
  hosts: localhost
  become: yes  # Ensure Ansible executes commands with sudo

  tasks:
    - name: Install required development libraries
      apt:
        name:
          - libxrandr-dev
          - libxinerama-dev
          - libxcursor-dev
          - libxi-dev
          - libgl-dev
        state: present

    - name: Clone MuJoCo repository from GitHub
      git:
        repo: https://github.com/openai/mujoco-py.git
        dest: /path/to/your/mujoco-py  # Specify your desired destination
        update: yes

    - name: Build MuJoCo
      command: >
        mkdir -p build &&
        cd build &&
        cmake .. &&
        cmake --build .
      args:
        chdir: /path/to/your/mujoco-py  # Adjust path to your cloned mujoco-py repository

    - name: Install Python dependencies
      pip:
        name:
          - 'glfw>=1.8.3'
          - requests
        executable: pip3  # Adjust if necessary
        virtualenv: /path/to/your/virtualenv  # Optional: Use if working in a virtual environment
        state: present
