---
- name: Install Kodi and PVR addons
  hosts: localhost
  become: yes  # Ensure Ansible executes commands with sudo

  tasks:
    - name: Install software-properties-common
      ansible.builtin.package:
        name: software-properties-common
        state: present

    - name: Add Kodi PPA repository
      ansible.builtin.apt_repository:
        repo: ppa:team-xbmc/ppa

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Kodi
      ansible.builtin.package:
        name: kodi
        state: present

    - name: Install Kodi PVR and audio decoder addons
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      with_items:
        - kodi-pvr-argustv
        - kodi-pvr-demo
        - kodi-pvr-dvbviewer
        - kodi-pvr-iptvsimple
        - kodi-pvr-mediaportal-tvserver
        - kodi-pvr-mythtv
        - kodi-pvr-nextpvr
        - kodi-pvr-njoy
        - kodi-pvr-hts
        - kodi-pvr-vdr-vnsi
        - kodi-pvr-vuplus
        - kodi-pvr-dvblink
        - kodi-pvr-filmon
        - kodi-pvr-hdhomerun
        - kodi-pvr-pctv
        - kodi-pvr-stalker
        - kodi-pvr-vbox
        - kodi-pvr-wmc
        - kodi-audiodecoder-modplug
        - kodi-audiodecoder-nosefart
        - kodi-audiodecoder-sidplay
        - kodi-audiodecoder-snesapu
        - kodi-audiodecoder-stsound
        - kodi-audiodecoder-timidity
        - kodi-audiodecoder-vgmstream
