---
- name: Install PyCharm Community Edition
  hosts: localhost
  become: yes

  tasks:
    - name: Download PyCharm Community Edition
      get_url:
        url: "https://download.jetbrains.com/python/pycharm-community-2023.3.tar.gz"
        dest: "/tmp/pycharm-community-2023.3.tar.gz"
        mode: '0644'

    - name: Extract PyCharm Community Edition
      ansible.builtin.command: "tar -xzf /tmp/pycharm-community-2023.3.tar.gz -C /opt/pycharm-community"

    - name: Move extracted files to versioned directory
      ansible.builtin.shell: "mv /opt/pycharm-community/pycharm-community-2023.3/* /opt/pycharm-community/2023.3"

    - name: Copy desktop file to system applications
      ansible.builtin.copy:
        src: "com.jetbrains.idea.desktop"
        dest: "/usr/share/applications/"
        mode: '0644'
        owner: root
        group: root
