---
- name: Install Firefox
  hosts: localhost
  become: yes
  tasks:
    - name: Create directory for Firefox
      file:
        path: /opt/firefox
        state: directory
        mode: '0755'

    - name: Download Firefox tarball
      get_url:
        url: https://download-installer.cdn.mozilla.net/pub/firefox/releases/116.0.1/linux-x86_64/en-US/firefox-116.0.1.tar.bz2
        dest: /tmp/firefox-116.0.1.tar.bz2
        mode: '0644'

    - name: Extract Firefox tarball
      ansible.builtin.unarchive:
        src: /tmp/firefox-116.0.1.tar.bz2
        dest: /opt/firefox
        remote_src: yes
        creates: /opt/firefox/firefox-116.0.1

    - name: Set up alternatives for Firefox
      ansible.builtin.alternatives:
        name: firefox
        link: /usr/bin/firefox
        path: /opt/firefox/firefox-116.0.1/firefox/firefox
        priority: 90
        state: present

    - name: Copy Firefox .desktop file
      copy:
        src: firefox.desktop
        dest: /usr/share/applications/firefox.desktop
        mode: '0644'

    - name: Update desktop database
      ansible.builtin.command:
        cmd: update-desktop-database

    - name: Verify Firefox installation
      command: firefox --version
      register: firefox_version_output

    - name: Display Firefox version
      debug:
        msg: "Firefox version is {{ firefox_version_output.stdout }}"

    - name: Clean up downloaded tarball
      file:
        path: /tmp/firefox-116.0.1.tar.bz2
        state: absent
