---
- name: Install Rust
  hosts: all
  become: yes
  tasks:
    - name: Install required packages
      apt:
        name:
          - curl
        state: present
      when: ansible_os_family == "Debian"

    - name: Install required packages
      yum:
        name:
          - curl
        state: present
      when: ansible_os_family == "RedHat"

    - name: Download rustup installation script
      get_url:
        url: https://sh.rustup.rs
        dest: /tmp/rustup-init.sh
        mode: 'u+x'

    - name: Install Rust using rustup
      command: /tmp/rustup-init.sh -y
      args:
        chdir: /tmp

    - name: Add cargo and rustc to PATH
      lineinfile:
        path: "{{ ansible_env.HOME }}/.profile"
        line: 'export PATH="$HOME/.cargo/bin:$PATH"'
        create: yes
        state: present

    - name: Update environment for current session
      shell: |
        export PATH="$HOME/.cargo/bin:$PATH"
        rustc --version
        cargo --version
      register: rust_versions
      args:
        executable: /bin/bash

    - name: Print rustc version
      debug:
        msg: "rustc version: {{ rust_versions.stdout_lines[0] }}"

    - name: Print cargo version
      debug:
        msg: "cargo version: {{ rust_versions.stdout_lines[1] }}"

    - name: Clean up installation script
      file:
        path: /tmp/rustup-init.sh
        state: absent
