---
- name: Install Rust
  hosts: all
  become: no  # Ensure that tasks are run as a non-root user
  tasks:
    - name: Install required packages
      package:
        name: curl
        state: present
      when: ansible_os_family == "Debian"

    - name: Install required packages
      package:
        name: curl
        state: present
      when: ansible_os_family == "RedHat"

    - name: Download rustup installation script
      get_url:
        url: https://sh.rustup.rs
        dest: /tmp/rustup-init.sh
        mode: 'u+x'

    - name: Install Rust using rustup
      command: /tmp/rustup-init.sh -y
      args:
        chdir: /tmp
      environment:
        CARGO_HOME: "{{ ansible_env.HOME }}/.cargo"
        RUSTUP_HOME: "{{ ansible_env.HOME }}/.rustup"

    - name: Ensure .cargo/bin is in PATH
      lineinfile:
        path: "{{ ansible_env.HOME }}/.bashrc"
        line: 'export PATH="$HOME/.cargo/bin:$PATH"'
        create: yes
        state: present

    - name: Source .bashrc and verify installations
      shell: |
        source "{{ ansible_env.HOME }}/.bashrc"
        rustc --version
        cargo --version
      register: rust_versions
      args:
        executable: /bin/bash

    - name: Print rustc version
      debug:
        msg: "rustc version: {{ rust_versions.stdout_lines[0] }}"

    - name: Print cargo version
      debug:
        msg: "cargo version: {{ rust_versions.stdout_lines[1] }}"

    - name: Clean up installation script
      file:
        path: /tmp/rustup-init.sh
        state: absent
