---
- name: Install CodeLite on Ubuntu
  hosts: localhost
  become: yes

  vars:
    codelite_repo_url: "https://repos.codelite.org/ubuntu/"

  tasks:
    - name: Gather facts
      ansible.builtin.setup:

    - name: Get Ubuntu version
      set_fact:
        ubuntu_version: "{{ ansible_distribution_release }}"

    - name: Add CodeLite public key
      apt_key:
        url: http://repos.codelite.org/CodeLite.asc
        state: present

    - name: Add CodeLite repository
      apt_repository:
        repo: "deb {{ codelite_repo_url }} {{ ubuntu_version }} universe"
        state: present

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install CodeLite
      apt:
        name: codelite
        state: present
