---
- name: Install Jellyfin Media Server
  hosts: localhost
  become: yes  # This allows Ansible to execute commands with sudo

  tasks:
    - name: Install apt-transport-https package
      ansible.builtin.apt:
        name: apt-transport-https
        state: present

    - name: Add Jellyfin repository key
      ansible.builtin.apt_key:
        url: https://repo.jellyfin.org/jellyfin_team.gpg.key
        state: present

    - name: Add Jellyfin repository to sources.list
      ansible.builtin.lineinfile:
        path: /etc/apt/sources.list.d/jellyfin.list
        line: "deb [arch={{ ansible_architecture }}] https://repo.jellyfin.org/{{ ansible_distribution | lower }} {{ ansible_codename }} main"
        create: yes

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Jellyfin
      ansible.builtin.apt:
        name: jellyfin
        state: present
        update_cache: yes

    - name: Enable Jellyfin service
      ansible.builtin.service:
        name: jellyfin
        enabled: yes
        state: started
