---
- name: Install goofys using Ansible
  hosts: localhost
  become: yes

  tasks:
    - name: Download goofys binary
      get_url:
        url: "https://github.com/kahing/goofys/releases/download/v0.24.0/goofys"
        dest: "/usr/local/bin/goofys"
        mode: '0755'  # Ensure executable permissions

    - name: Set owner and group for goofys binary
      file:
        path: "/usr/local/bin/goofys"
        owner: root
        group: root
        mode: '0755'

    - name: Verify goofys installation
      stat:
        path: "/usr/local/bin/goofys"
      register: goofys_installed

    - name: Print goofys version if installed
      debug:
        msg: "goofys installed successfully."
      when: goofys_installed.stat.exists
