---
- name: Install Docker on Ubuntu 22.04
  hosts: localhost
  become: yes

  tasks:
    - name: Update APT package index
      apt:
        update_cache: yes

    - name: Install prerequisite packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common

    - name: Add Docker GPG key
      shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch={{ dpkg_architecture }} signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

    - name: Update APT package index (again)
      apt:
        update_cache: yes

    - name: Check Docker CE version candidates
      command: apt-cache policy docker-ce
      register: docker_ce_version

    - name: Install Docker CE
      apt:
        name: docker-ce
        state: present
      when: "'docker-ce' not in docker_ce_version.stdout"

    - name: Start Docker service and enable on boot
      service:
        name: docker
        state: started
        enabled: yes

    - name: Check Docker service status
      systemd:
        name: docker
        state: started

    - name: Display Docker version
      command: docker --version
      register: docker_version

    - debug:
        msg: "Docker version is {{ docker_version.stdout }}"
