---
- name: Install Amazon Corretto 11 on Debian-based Linux
  hosts: localhost
  become: yes  # This allows Ansible to execute commands with sudo

  tasks:
    - name: Import Corretto public key
      ansible.builtin.apt_key:
        url: https://apt.corretto.aws/corretto.key
        state: present

    - name: Add Corretto repository
      ansible.builtin.apt_repository:
        repo: 'deb https://apt.corretto.aws stable main'
        state: present

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Amazon Corretto 11 JDK
      ansible.builtin.apt:
        name: java-11-amazon-corretto-jdk
        state: present
        update_cache: yes
